/*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Test class for the CustomerViewDashboardsController class
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Initial implementation
* @author         Lucian Ciobanu   <lucian.ciobanu@deutoria.com>
* @created        2016-06-21
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Changes
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
*/
@isTest
public class CustomerViewDashboardsControllerTest {
    
    public static testMethod void testClass() {
    	
    	Test.startTest();
    	
    	CustomerViewDashboardsController ctrl = new CustomerViewDashboardsController();
    	
    	Test.stopTest();
    	
    }
    
}